[project]
name = "monodemo"
dependencies = [
    "flask",
    "pybind11>=2.13.1",
    "foo @ file:///${PROJECT_ROOT}/foo",
]


[tool.rye]
managed = true
virtual = true
dev-dependencies = [
    "pytest>=8.3.1",
]
